# File-based labels
documentation:
  - changed-files:
      - "docs/**"
      - "**/*.md"

source:
  - changed-files:
      - "src/**/*"
      - "!src/docs/**"

# Branch-based labels
feature:
  - head-branch:
      - regex: '^feature/.*'

bugfix:
  - head-branch:
      - regex: '^bugfix.*'
      - regex: '^fix.*'

improvement:
  - head-branch:
      - regex: '^improvement.*'
      - regex: '^refactor.*'
