# File-based labels
documentation:
  - changed-files:
      any:
        - "docs/**"
        - "**/*.md"

source:
  - changed-files:
      any:
        - "src/**/*"
      not:
        - "src/docs/**"

# Branch-based labels
feature:
  - head-branch:
      - regex: '^feature/.*'

bugfix:
  - head-branch:
      - regex: '^bugfix.*'
      - regex: '^fix.*'

improvement:
  - head-branch:
      - regex: '^improvement.*'
      - regex: '^refactor.*'
