documentation:
- changed-files:
  - any-glob-to-any-file:
      - docs/**
      - "**/*.md"

source:
- changed-files:
  - any-glob-to-any-file:
      - src/**/*
      - "!src/docs/**"

feature:
- head-branch:
  - regex: '^feature'
  - regex: 'feature'

bugfix:
- head-branch:
  - regex: '^bugfix'
  - regex: 'bugfix'
  - regex: '^fix'
  - regex: 'fix'

improvement:
- head-branch:
  - regex: '^improvement'
  - regex: 'improvement'
  - regex: '^refactor'
  - regex: 'refactor'
