 name: ✨ Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: "Currently it’s hard to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: "I’d like to see..."

  - type: checkboxes
    id: scope
    attributes:
      label: Area
      options:
        - label: UI / UX
        - label: Backend
        - label: Performance
        - label: API
        - label: Documentation

  - type: dropdown
    id: priority
    attributes:
      label: Priority (your opinion)
      options:
        - Nice to have
        - Important
        - Critical

