 name: ❓ Question
description: Ask a usage or behavior question
title: "[Question]: "
labels: ["question"]

body:
  - type: textarea
    id: question
    attributes:
      label: What’s your question?
    validations:
      required: true

